import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'

import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
} from "@/components/ui/navigation-menu";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <header className="flex justify-between items-center p-5">
            <h2>Logo</h2>
            <NavigationMenu>
              <NavigationMenuList>
                <NavigationMenuLink>
                  <Link href="/about">About</Link>
                </NavigationMenuLink>
                <NavigationMenuLink>
                  <Link href="/courses">Courses</Link>
                </NavigationMenuLink>
                <NavigationMenuLink>
                  <Link href="/pages">Pages</Link>
                </NavigationMenuLink>
                <NavigationMenuLink>
                  <Link href="/blog">Blog</Link>
                </NavigationMenuLink>
                <NavigationMenuLink>
                  <Link href="/contact">Contact Us</Link>
                </NavigationMenuLink>
                <NavigationMenuItem>
                  {/* <Button
                    className="bg-violet-500 cursor-pointer"
                    variant="outline"
                  >
                    Register
                  </Button> */}
                  <Show when="signed-out">
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </Show>
            <Show when="signed-in">
              <UserButton />
            </Show>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
